#' @export
get_checklists <- function() {
  list(
    R = c(
      "script renders free of error",
      "helper functions are easily accessible",
      "relative paths are used"
    ),
    mod = c(
      "units match those in specification file",
      "seeds are consistent",
      "differential equations inputted correctly"
    ),
    cpp = c(
      "code is easily readable",
      "code follows style guidelines",
      "comments explain non-standard coding conventions"
    ),
    vpc = c(
      "confidence interval is 95%",
      "500 simulations ran",
      "generated figures match"
    ),
    setup = c(
      "Correct dataset used. Any modifications appropriate and documented.",
      "Exclusion of anomalous concentration appropriate (if applicable).",
      "Correct units for time and concentration variable specified. Use CDISC SDTM Controlled Terminology UNIT. If dataset (WATSON) may not apply.",
      "Any negative pre-dose times set to zero (only if applicable).",
      "Filtered for ‘ANL03L’ to include ‘Y’ if ANL03L column (only if present in dataset)."
    ),
    NCA = c(
      "Source data mapped correctly.",
      "Time and concentration variables mapped correctly.",
      "Model type selected appropriately (dependent of route of administration).",
      "Dosing set-up appropriately includes unit.",
      "Partial areas named and included appropriately (if applicable). \nUse CDISC SDTM Controlled Terminology PKPARMCD and suffix with the time interval in parentheses; e.g. AUCINT(0-12) if dataset was generated by Biostatistics e.g. (DOMINO). \nIf dataset (WATSON) may not apply.",
      "Calculation method for area under the curve (AUC) is assigned as linear up/logarithmic down (unless otherwise specified with rationale).",
      "Weighting is assigned as uniform (unless otherwise specified with rationale).",
      "Points for regression slopes selected appropriately. See considerations in slope selection for determination of lambda_z and associated parameters row of this checklist. \nIf dataset (WATSON) may not apply.",
      "Associated PK parameters are output/included in workbook (if applicable). \nE.g. TLST associated AUCLST; AUCPEO associated to AUCINF; AUMCINF associated to AUMCPEO; LAMZ, LAMZLL, LAMZUL and R2 associated with LAMZHL. \nIf dataset (WATSON) may not apply."
    ),
    outputs = c(
      "Final Parameters (_param.csv), Summary Table (_summ.csv) and Dosing (_dosing.csv) files named appropriately. E.g. Name_param.csv, where Name is the Dataset filename.",
      "ND and NC assignment done correctly. If dataset (WATSON) may not apply."
    ),
    tables_and_figures = c(
      "Units correctly assigned.",
      "Figure axes names and legends assigned correctly.",
      "Data summary correct (e.g. by ID, analyte, matrix, day, dose, sex, etc.).",
      "Correct summary statistics included (typically N, Geometric mean, gCV%, median, range)."
    )
  )
}

#' @export
create_file_data_structure <- function(file_name, assignees = NULL, checklist_type = NULL, checklists = get_checklists()) {
  # if checklist_type wasn't given, make it the file ext
  if (is.null(checklist_type)) {
    file_extension <- tools::file_ext(file_name)
    checklist_type <- file_extension

  }

  file_data <- list(
    name = file_name,
    checklist_type = checklist_type
  )

  if (!is.null(assignees)) {file_data$assignees = assignees}

  file_data$items <- checklists[[checklist_type]]

  file_data
}

# files should be a list of lists like this:
# list(
#   list(
#     name = name1,
#     assignees = assignees1,
#.    checklist_type = type1,
#     items = items1
#   ),
#   list(
#     name = name2,
#     assignees = assignees2,
#.    checklist_type = type2,
#     items = items2
#   ),
#   list(
#     name = name3,
#     assignees = assignees3,
#.    checklist_type = type3,
#     items = items3
#   ),
#  ...
# )

#### Example output

# owner: A2-Ai
# repo: test-qc-api
# files:
# - name: file1.cpp
#   checklist_type: cpp
#   assignees: jenna-a2ai
#   items:
#   - code is easily readable
#   - code follows style guidelines
#   - comments explain non-standard coding conventions
# - name: file1.R
#   checklist_type: vpc
#   assignees: jenna-a2ai
#   items:
#   - confidence interval is 95%
#   - 500 simulations given
#   - generated figures match
#' @export
create_yaml <- function(name,
                        repo,
                        files, # files must be a list of lists not a vector of lists
                        milestone = NULL,
                        description = NULL
                        ) {
  # hard code owner
  owner <- get_organization() #"a2-ai-tech-training"

  data <- list(
    owner = owner,
    repo = repo,
    files = files # files must be a list of lists not a vector of lists
  )

  if (!is.null(milestone) && milestone != "") {data$milestone = milestone}
  if (!is.null(description) && description != "") {data$description = description}

  # make into yaml string
  yaml_string <- yaml::as.yaml(data)
  # validate contents
  validate_yaml_contents(data)
  # make path
  yaml_path <- file.path(paste0(name, ".yaml"))
  withr::defer_parent(fs::file_delete(yaml_path))
  # create yaml
  write(yaml_string, file = yaml_path)

  yaml_path
}
