new_qc_checklists <- function() {
  list(
    NCA = "Note: This checklist is NOT an exhaustive list of all checks. User is encouraged to personalise checklist for individual study needs.
### Set-up
- [ ] Correct dataset used. Any modifications appropriate and documented.
- [ ] Exclusion of anomalous concentration appropriate (if applicable).
- [ ] Correct units for time and concentration variable specified. Use CDISC SDTM Controlled Terminology UNIT. If dataset (WATSON) may not apply.
- [ ] Any negative pre-dose times set to zero (only if applicable)
- [ ] Filtered for ‘ANL03L’ to include ‘Y’ if ANL03L column (only if present in dataset).

### NCA
- [ ] Source data mapped correctly.
- [ ] Time and concentration variables mapped correctly.
- [ ] Model type selected appropriately (dependent of route of administration).
- [ ] Dosing set-up appropriately includes unit.
- [ ] Partial areas named and included appropriately (if applicable). Use CDISC SDTM Controlled Terminology PKPARMCD and suffix with the time interval in parentheses; e.g. AUCINT(0-12) if dataset was generated by Biostatistics e.g. (DOMINO). If dataset (WATSON) may not apply.
- [ ] Calculation method for area under the curve (AUC) is assigned as linear up/logarithmic down (unless otherwise specified with rationale).
- [ ] Weighting is assigned as uniform (unless otherwise specified with rationale).
- [ ] Points for regression slopes selected appropriately. See considerations in slope selection for determination of lambda_z and associated parameters row of this checklist. If dataset (WATSON) may not apply.
- [ ] Associated PK parameters are output/included in workbook (if applicable). E.g. TLST associated AUCLST; AUCPEO associated to AUCINF; AUMCINF associated to AUMCPEO; LAMZ, LAMZLL, LAMZUL and R2 associated with LAMZHL. If dataset (WATSON) may not apply.

### Outputs
- [ ] Final Parameters (_param.csv), Summary Table (_summ.csv) and Dosing (_dosing.csv) files named appropriately. E.g. Name_param.csv, where Name is the Dataset filename.
- [ ] ND and NC assignment done correctly. If dataset (WATSON) may not apply.

### Tables/Figues
- [ ] Units correctly assigned.
- [ ] Figure axes names and legends assigned correctly.
- [ ] Data summary correct (e.g. by ID, analyte, matrix, day, dose, sex, etc.).
- [ ] Correct summary statistics included (typically N, Geometric mean, gCV%, median, range).

### Considerations in slope selection for determination of LAMZ and associated parameters
- [ ] A minimum of three points are to be included in the slope determination; the reliability of lambda_z and associated parameters should also be considered as follows:

    1) Linear regression of logarithmically transformed concentration versus time data will be used for slope determination.

    2) Only those data points judged to describe the terminal log-linear decline will be used in the regression.

    3) The duration of time over which lambda_z is estimated should be at least 2 times the subsequently estimated terminal phase half-life (t1/2) to be reliably estimated. Deviation from this is acceptable if clearly documented.

    4) The associated regression coefficient (r2) should be ³ 0.85. Deviation from this is acceptable if clearly documented.

    5) The percentage of AUC(0-inf) obtained by extrapolation should be < 20%. Deviation from this is acceptable if clearly documented and at least 80% of the profiles in the study have <20% of the AUC(0-inf) as extrapolated area. It is unacceptable to use AUC(0-inf) data if >40% of the AUC(0-inf) has been extrapolated, except in specific situations which should be carefully justified.\n"
    ,
    report = "Note: This checklist is NOT an exhaustive list of all checks. User is encouraged to personalise checklist for individual study needs.
### Front page
- [ ] Accuracy of front page

### Table of Contents (if applicable)
- [ ] Ensure included, if applicable

### Summary (if applicable)
- [ ] Summary text, tables/figures and numerical values checked against Report Body Text

### Report Body Text
- [ ] Numbers reported in text correspond to numbers in tables, listings and output
- [ ] Check that all cited references are included in the reference list
- [ ] If changes were made to the dataset, are they documented and justified in the report?
- [ ] Correct units
- [ ] Consistent significant figures
- [ ] Headings correct
- [ ] All analysis changes referred to

### Tables/Figures/Listings
- [ ] Titles correct
- [ ] Tables, figures and listings imported correctly
- [ ] Footnote and source references accurate

### References (if applicable)
- [ ] Quoted correctly

### Appendix (if applicable)
- [ ] Titles correct
- [ ] Tables, figures, models, scripts imported correctly\n")

}
